# Generated by Django 4.2.11 on 2024-04-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AssetName", models.CharField(max_length=255)),
                ("Category", models.CharField(max_length=100)),
                ("Department", models.CharField(max_length=100)),
                ("Office", models.CharField(max_length=100)),
                ("Location", models.CharField(max_length=100)),
                ("Status", models.CharField(max_length=100)),
                ("PurchaseDate", models.DateField()),
                ("PurchasePrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Depreciation", models.DecimalField(decimal_places=2, max_digits=10)),
                ("WarrantyExpirationDate", models.DateField()),
                ("AssignedTo", models.CharField(max_length=100)),
                ("LastMaintenanceDate", models.DateField()),
                ("NextMaintenanceDate", models.DateField()),
                ("Supplier_id", models.IntegerField()),
                ("SerialNumber", models.CharField(max_length=100)),
                ("Model", models.CharField(max_length=100)),
            ],
        ),
    ]
