# Generated by Django 4.2.11 on 2024-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="AssignedTo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="Depreciation",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="LastMaintenanceDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="Location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="Model",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="NextMaintenanceDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="Office",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="PurchaseDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="PurchasePrice",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="SerialNumber",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="Status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="Supplier_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="WarrantyExpirationDate",
            field=models.DateField(null=True),
        ),
    ]
